apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metrics-app-service-monitor
  namespace: metrics
spec:
  selector:
    matchLabels:
      app: metrics-app
  endpoints:
    - port: http
      path: "/actuator/prometheus"